regions:
- "us-east-1"
- "us-west-2"

blocklist:
- 886436967273

accounts:
  # Replace with the accounts you want to clean
  481665124648:
    presets:
    - "common"
    - "sso"
  779846813173:
    presets:
    - "common"
    - "sso"

resource-types:
  # Specifying this in the configuration will ensure that these resources
  # will be specifically excluded from aws-nuke during its run.
  excludes:
  # Excluding some deprecated services
  - ElasticTranscoderPipeline
  - Cloud9Environment
  - FMSNotificationChannel
  - MachineLearningBranchPrediction
  - OpsWorksCMServer
  - OpsWorksCMBackup
  - OpsWorksCMServerState
  - OpsWorksApp
  - OpsWorksUserProfile
  - OpsWorksInstance
  - OpsWorksLayer
  - RoboMakerRobotApplication
  - RoboMakerSimulationJob
  # ....

presets:
  sso:
    filters:
      IAMSAMLProvider:
      - type: "regex"
        value: "AWSSSO_.*_DO_NOT_DELETE"
      IAMRole:
      - type: "glob"
        value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
      - type: "glob"
        value: "AWSReservedSSO_*"
  common:
    filters:
      IAMRole:
      - "OrganizationAccountAccessRole"
